// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api-go/ent/user"
	"api-go/schemas"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schemas.User{}.Fields()
	_ = userFields
	// userDescDeleted is the schema descriptor for deleted field.
	userDescDeleted := userFields[3].Descriptor()
	// user.DefaultDeleted holds the default value on creation for the deleted field.
	user.DefaultDeleted = userDescDeleted.Default.(bool)
	// userDescCreated is the schema descriptor for created field.
	userDescCreated := userFields[4].Descriptor()
	// user.DefaultCreated holds the default value on creation for the created field.
	user.DefaultCreated = userDescCreated.Default.(func() time.Time)
}
