apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: valkey-app
  template:
    metadata:
      labels:
        app: valkey-app
    spec:
      containers:
        - name: valkey-container
          imagePullPolicy: Always
          image: valkey/valkey:8.0.0
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: valkey-service
spec:
  selector:
    app: valkey-app
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
