apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocodb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nocodb
  template:
    metadata:
      labels:
        app: nocodb
    spec:
      containers:
        - name: nocodb
          image: nocodb/nocodb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          envFrom:
            - secretRef:
                name: nocodb-secret
          env:
            - name: PORT
              value: "8080"
            - name: NC_PUBLIC_URL
              value: "https://nocodb.[domain]"
            - name: NC_TOOL_DIR
              value: "/usr/app/data"
            - name: NC_DISABLE_TELE
              value: "true"
            - name: NC_REDIS_URL
              value: "redis://valkey-service:6379"
          volumeMounts:
            - name: nocodb-data
              mountPath: /usr/app/data
      volumes:
        - name: nocodb-data
          persistentVolumeClaim:
            claimName: nocodb-data
---
apiVersion: v1
kind: Service
metadata:
  name: nocodb
spec:
  selector:
    app: nocodb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nocodb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nocodb
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: nocodb-ip
    networking.gke.io/managed-certificates: nocodb-certificate
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: nocodb
                port:
                  number: 8080
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: nocodb-certificate
spec:
  domains:
    - nocodb.[domain]
