name: Go Testing

on:
  push:
    branches: ["develop"]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.5"

      - name: Go Build
        run: |
          cd api-v1
          go mod download
          go build api.go

      - name: Go Test
        run: |
          cd api-v1
          go test -v ./...
